<?php
// +----------------------------------------------------------------------
// | PHP [ JUST YOU ]
// +----------------------------------------------------------------------
// | Copyright (c) 2017~2017 http://www.jyphp.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: Albert <albert_p@foxmail.com>
// +----------------------------------------------------------------------
namespace JYPHP\Core\Console;

use JYPHP\Core\Interfaces\Console\IApplication;
use Symfony\Component\Console\Application as SymfonyApplication;
use Symfony\Component\Console\Output\OutputInterface;

class Application extends SymfonyApplication implements IApplication
{

    public function renderException(\Exception $e, OutputInterface $output)
    {
        parent::renderException($e, $output); // TODO: Change the autogenerated stub
    }
}